export function renderHome() {
  return `<!doctype html>
<html lang="th">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>SPTracking — เช็กราคาสินค้า Shopee</title>
<style>
:root{color-scheme:light;--bg:#f6f7fb;--card:#fff;--text:#1f2937;--muted:#6b7280;--line:#e5e7eb;--accent:#ee4d2d;--accent2:#ff7a45;--good:#059669;--warn:#b45309}
*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",Tahoma,sans-serif;background:var(--bg);color:var(--text)}
.wrap{max-width:980px;margin:0 auto;padding:28px 18px 56px}.hero{text-align:center;padding:28px 0 22px}.brand{font-size:34px;font-weight:800}.brand span{color:var(--accent)}.sub{color:var(--muted);margin-top:7px}.search{display:flex;gap:10px;background:var(--card);padding:12px;border-radius:18px;box-shadow:0 8px 28px rgba(31,41,55,.08)}input{flex:1;border:1px solid var(--line);border-radius:12px;padding:14px 16px;font-size:15px;outline:none}input:focus{border-color:#fb8b74;box-shadow:0 0 0 3px rgba(238,77,45,.12)}button{border:0;border-radius:12px;padding:0 22px;background:linear-gradient(135deg,var(--accent),var(--accent2));color:white;font-weight:700;cursor:pointer}.hint{font-size:13px;color:var(--muted);margin:9px 4px 22px}.status{display:none;margin:16px 0;padding:14px 16px;border-radius:12px;background:#fff;border:1px solid var(--line)}.status.show{display:block}.status.warn{border-color:#fed7aa;background:#fff7ed;color:#9a3412}.status.bad{border-color:#fecaca;background:#fef2f2;color:#991b1b}
.card{background:var(--card);border:1px solid var(--line);border-radius:18px;padding:20px;box-shadow:0 7px 22px rgba(31,41,55,.05)}#result{display:none}.title{font-size:20px;font-weight:750;line-height:1.4}.variant{color:var(--muted);margin-top:3px}.price{font-size:38px;font-weight:850;color:var(--accent);margin:18px 0}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.stat{border:1px solid var(--line);border-radius:14px;padding:14px}.stat small{display:block;color:var(--muted);margin-bottom:5px}.stat strong{font-size:20px}.meta{display:flex;gap:16px;flex-wrap:wrap;color:var(--muted);font-size:13px;margin-top:14px}.chartbox{margin-top:18px;border-top:1px solid var(--line);padding-top:16px}.charthead{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}.chart{width:100%;height:280px;border-radius:12px;background:#fafafa}.recent{margin-top:24px}.recent h3{font-size:16px}.recent-list{display:grid;gap:8px}.recent-item{display:flex;justify-content:space-between;gap:12px;align-items:center;background:#fff;border:1px solid var(--line);border-radius:12px;padding:11px 13px;cursor:pointer}.recent-item:hover{border-color:#f6a08e}.recent-item span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.pill{font-size:12px;color:var(--muted)}
@media(max-width:640px){.wrap{padding:18px 12px 38px}.hero{padding-top:14px}.brand{font-size:28px}.search{flex-direction:column}.search button{height:46px}.stats{grid-template-columns:1fr}.price{font-size:32px}.chart{height:220px}}
</style>
</head>
<body><main class="wrap">
<section class="hero"><div class="brand">SP<span>Tracking</span></div><div class="sub">ดูว่าราคาตอนนี้ถูกหรือยัง จากประวัติราคาที่เราเก็บไว้</div></section>
<section class="search"><input id="url" placeholder="วางลิงก์สินค้า Shopee ที่เลือกตัวเลือกสินค้าแล้ว"><button id="go">เช็กราคา</button></section>
<div class="hint">แนะนำให้ใช้ลิงก์ที่มีรุ่น/ตัวเลือกสินค้าอยู่ใน URL เพื่อดูประวัติของรุ่นนั้นโดยตรง</div>
<div id="status" class="status"></div>
<section id="result" class="card">
  <div class="title" id="name"></div><div class="variant" id="variant"></div><div class="price" id="price"></div>
  <div class="stats"><div class="stat"><small>ต่ำสุด</small><strong id="low">-</strong></div><div class="stat"><small>สูงสุด</small><strong id="high">-</strong></div><div class="stat"><small>เฉลี่ย</small><strong id="avg">-</strong></div></div>
  <div class="meta"><span id="obs"></span><span id="checked"></span><span id="stock"></span></div>
  <div class="chartbox"><div class="charthead"><strong>ประวัติราคา</strong><span class="pill">ใหม่ → เก่าใน API / กราฟเรียงตามเวลา</span></div><canvas id="chart" class="chart"></canvas></div>
</section>
<section class="recent"><h3>ดูล่าสุดในเครื่องนี้</h3><div id="recent" class="recent-list"></div></section>
</main>
<script>
const $=id=>document.getElementById(id), fmt=n=>n==null?'-':'฿'+Number(n).toLocaleString('th-TH',{maximumFractionDigits:2});
const status=(msg,kind='')=>{const e=$('status');e.className='status show '+kind;e.textContent=msg};
$('go').onclick=lookup;$('url').addEventListener('keydown',e=>{if(e.key==='Enter')lookup()});
async function lookup(raw){const value=typeof raw==='string'?raw:$('url').value.trim();if(!value)return status('วางลิงก์ Shopee ก่อน','warn');$('url').value=value;status('กำลังค้นหาประวัติราคา...');$('result').style.display='none';
 try{const r=await fetch('/api/lookup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url:value})});const d=await r.json();if(!r.ok||!d.ok){if(d.code==='NOT_TRACKED') return status('ยังไม่มีประวัติของรุ่นนี้ในระบบ — เปิดลิงก์นี้ใน Shopee ด้วย SPTracking Extension แล้วรีเฟรชหน้า 1 ครั้ง จากนั้นกลับมาเช็กอีกครั้ง','warn');if(d.code==='MODEL_REQUIRED') return status('ลิงก์นี้ยังไม่ระบุรุ่นสินค้า กรุณาเลือกตัวเลือกสินค้าใน Shopee แล้วคัดลอกลิงก์ใหม่','warn');throw new Error(d.error||'Lookup failed')}render(d);saveRecent(value,d);status('พบประวัติราคาแล้ว') }catch(e){status('เช็กราคาไม่สำเร็จ: '+e.message,'bad')}}
function render(d){$('result').style.display='block';$('name').textContent=d.product_name||'สินค้า Shopee';$('variant').textContent=d.variation_name||('model '+d.model_id);$('price').textContent=fmt(d.current_price);$('low').textContent=fmt(d.stats?.lowest);$('high').textContent=fmt(d.stats?.highest);$('avg').textContent=fmt(d.stats?.average);$('obs').textContent='บันทึก '+(d.stats?.observations||0)+' ครั้ง';$('checked').textContent='อัปเดต '+new Date(d.last_checked_at).toLocaleString('th-TH');$('stock').textContent=d.stock_status==='OUT_OF_STOCK'?'สินค้าหมด':'สถานะ '+(d.stock_status||'ไม่ทราบ');draw(d.history||[])}
function draw(rows){const c=$('chart'),ratio=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*ratio;c.height=h*ratio;const x=c.getContext('2d');x.scale(ratio,ratio);x.clearRect(0,0,w,h);const data=[...rows].reverse();if(!data.length){x.fillStyle='#6b7280';x.font='14px sans-serif';x.fillText('ยังไม่มีข้อมูล',18,30);return}const vals=data.map(r=>r.price),min=Math.min(...vals),max=Math.max(...vals),pad=38,range=Math.max(1,max-min);x.strokeStyle='#e5e7eb';x.lineWidth=1;for(let i=0;i<4;i++){let y=pad+(h-pad*2)*i/3;x.beginPath();x.moveTo(pad,y);x.lineTo(w-pad,y);x.stroke()}x.strokeStyle='#ee4d2d';x.lineWidth=3;x.beginPath();data.forEach((r,i)=>{const px=pad+(w-pad*2)*(data.length===1?.5:i/(data.length-1));const py=h-pad-(r.price-min)/range*(h-pad*2);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();x.fillStyle='#ee4d2d';data.forEach((r,i)=>{const px=pad+(w-pad*2)*(data.length===1?.5:i/(data.length-1));const py=h-pad-(r.price-min)/range*(h-pad*2);x.beginPath();x.arc(px,py,4,0,Math.PI*2);x.fill()});x.fillStyle='#6b7280';x.font='12px sans-serif';x.fillText(fmt(max),6,pad+4);x.fillText(fmt(min),6,h-pad+4)}
function saveRecent(url,d){let a=[];try{a=JSON.parse(localStorage.getItem('sptracking_recent')||'[]')}catch{}a=a.filter(x=>x.url!==url);a.unshift({url,name:d.product_name,variant:d.variation_name,price:d.current_price});localStorage.setItem('sptracking_recent',JSON.stringify(a.slice(0,8)));renderRecent()}
function renderRecent(){let a=[];try{a=JSON.parse(localStorage.getItem('sptracking_recent')||'[]')}catch{}const box=$('recent');box.innerHTML='';if(!a.length){box.innerHTML='<div class="pill">ยังไม่มีรายการล่าสุด</div>';return}a.forEach(it=>{const e=document.createElement('div');e.className='recent-item';e.innerHTML='<span><b></b><br><small></small></span><strong></strong>';e.querySelector('b').textContent=it.name||'สินค้า Shopee';e.querySelector('small').textContent=it.variant||'';e.querySelector('strong').textContent=fmt(it.price);e.onclick=()=>lookup(it.url);box.appendChild(e)})}renderRecent();
</script></body></html>`;
}
